### ISSUE TITLE
Maybe one help patch

### ISSUE THREAD

**Issue by charlesneimog** [derekxkwan/pd-kellylochbaum#1]
Hi,

I understood that this is experiment, but could you provide one help patch?

Thanks

**Comment by derekxkwan** [comment]
ah sorry, i haven't thought about this for a long time, it was a basically a one-off thing that i haven't really thought about since so i wouldn't know what's going on here anymore (so i should probably archive this). feel free to fork. i think back then i basically referred to references I found on the ccrma website like so: [https://ccrma.stanford.edu/~jos/SMAC03S/Kelly_Lochbaum_Vocal_Tract_Model.html](https://ccrma.stanford.edu/~jos/SMAC03S/Kelly_Lochbaum_Vocal_Tract_Model.html) [https://ccrma.stanford.edu/~bilbao/master/node4.html](https://ccrma.stanford.edu/~bilbao/master/node4.html) [https://ccrma.stanford.edu/~jos/pasp/Singing_Kelly_Lochbaum_Vocal_Tract.html](https://ccrma.stanford.edu/~jos/pasp/Singing_Kelly_Lochbaum_Vocal_Tract.html)
